### ISSUE TITLE
Simpson's paradox in regression?

### ISSUE THREAD

**Issue by traceybit** [jcvdav/GitHubCol#1]
@jcvdav Looks like there might be a problem in estimating the relationship.  The figure created in the chunk code beginning in [L50](https://github.com/jcvdav/GitHubCol/blob/master/docs/manuscript.Rmd#L50) each species shows a clear positive trend. Perhaps we should fit three distinct lines?

**Comment by jcvdav** [comment]
Looks about right. I'm about to leave for the field, can you take care of it?
